from app.models import db, Project

def seed_projects():
    QueensGambit = Project(
        user_id = 1, title = 'Queen\'s Gambit', description = 'White immediately responds to Black\'s attempt to gain a foothold in the center by striking out with their c-pawn. Though this pawn is not defended and Black can capture it with ... dxc4, doing so will remove Black\'s d-pawn from the center and give White more opportunities for central control. Therefore, Black often chooses to decline the gambit, which he can do in several ways.', category_id = 1, views = 0, favorites = 0, supplies_text = None, supplies_image = None
    )
    QueensGambitAccepted = Project(
        user_id = 1, title = 'Queen\'s Gambit Accepted', description = 'The Queen\'s Gambit Accepted has a rich heritage in chess, both sides played by many of the world champions through the years. It is not really much of a gambit since white can recover the pawn immediately with 3. Qa4+, though unless white wants the queen placed on c4, this is unnecessary.', category_id = 1, views = 0, favorites = 0, supplies_text = None, supplies_image = None
    )
    QueensGambitDeclined = Project(
        user_id = 1, title = 'Queen\'s Gambit Declined', description = 'With 2...e6, Black declines the Queen\'s Gambit in the traditional fashion. 2...e6 bolsters the d5 pawn and opens a diagonal for the development of Black\'s dark-squared bishop. However, 2...e6 also blocks the c8-h3 diagonal for Black\'s light-squared bishop. Finding a way to productively develop this piece is a perennial challenge for Black players in the QGD.', category_id = 1, views = 0, favorites = 0, supplies_text = None, supplies_image = None
    )
    Italian = Project(
        user_id = 1, title = 'The Italian Game', description = 'And so we reach the Italian Game. White takes aim at Black\'s weak f7 pawn. Now there are a number of options for Black. This opening is more reserved than the Ruy Lopez.', category_id = 1, views = 0, favorites = 0, supplies_text = None, supplies_image = None
    )
    RuyLopez = Project(
        user_id = 1, title = 'The Ruy Lopez', description = 'The essential move marking the Ruy Lopez, or Spanish Game. "It is the double king\'s pawn opening most commonly used in master play; it has been adopted by almost all players at some point in their careers and many play it from both the White and Black sides. White threatens to trade off Black\'s c6-knight, leaving the e5-pawn undefended. It\'s not an immediate threat, because after 4. Bxc6 dxc6 5. Nxe5, Black can win the pawn back with 5... Qd4 or 5... Qg5. Black can respond in a variety of ways. The most common move is the Morphy Defence 3... a6. This forces White to make a decision about the Bishop - retreat or exchange. Many other moves are available, some neglecting completely the protection of the knight and the pawn and continuing development. The opening is named after the 16th century Spanish priest Ruy López de Segura.', category_id = 1, views = 0, favorites = 0, supplies_text = None, supplies_image = None
    )


    db.session.add(QueensGambit)
    db.session.add(QueensGambitAccepted)
    db.session.add(QueensGambitDeclined)
    db.session.add(Italian)
    db.session.add(RuyLopez)
    db.session.add(Project(user_id=9, category_id=3, title="Pseudo-Random Number Table", description="Games have myriad uses for randomization, but in many cases the constraints on this type of randomization can differ greatly from cryptography and other uses of random number generation. For one, many genres where sharing a generated layout or route can be a feature, generating those results from an initial seed instead of generating the results in the moment can be beneficial. Of course, this is technically not random as reliably producing the same result from the same initial condition is actually a deterministic behavior, but because of the practical unpredictability desired for this system, we'll continue to refer to them as \"random numbers\".\n\nAnother key difference is that game random number generation rarely requires the generation process to take time as cryptography does to mitigate brute force attacks; because random number generation is used to determine the results of events in the game, resolving those results quickly can prevent hold-ups in gameplay.", supplies_image="/images/project-rnTable/table-supplies.png", supplies_text="Initially I had written my own hashing function for this table generator, but found that tuning it so that numbers wouldn't clump was very difficult. While clumps are indeed an important part of randomized sequences, the in the case of a game, the appearance of randomness should be prioritized, and thus the results of the has shouldn't have frequent or long running clumps if possible. After some testing, it was discovered that sha256 suitably met the previously discussed concerns. Fortunately for my JavaScript implementation, sha256 is accessible via the built-in library crypto."))
    db.session.add(Project(user_id=9, category_id=3, title="Game Balance", description="Balancing a game can seem daunting with all the moving parts. One way to formalize the process, commonly referred to as the Sid Meier Method, helps maximize the progress towards a balanced state per iteration. Similar to Newton's Method of finding numerical solutions, the method tracks previous state as it progresses toward the desired state.", supplies_text="", supplies_image=""))
    db.session.add(Project(user_id=9, category_id=3, title="Abitrary Ranges from a Random Number Table", description="After creating a table with random (enough) data, progressing through the table in a way that accommodates odds that are not powers of the base of the table can be difficult. This project will demonstrate a strategy that mitigates the bias introduced by using odds that the number base is less divisible by.", supplies_text="This implementation requires an index to keep track of where in the random number table the next number will be read from. It's also possible to have track multiple indices if different events should not effect the results of each other (eg keeping enemy movements from affecting item drops). Of course, it also requires a random number table, an implementation of which is covered at \"this link\".", supplies_image="/images/project-range/range-supplies.png"))
    db.session.add(Project(user_id=9, category_id=3, title="Factory Pattern Room Loader", description="In the following code snippet I tackled the problem of randomly selecting a room template of a specified category from a pool of rooms. I used factory pattern in this implementation to encapsulate the list of room templates from the module that was doing the selecting and allow individual rooms to appear in multiple categories.", supplies_text="This implementation requires a hash table. Each entity category should point to an array of all the entities that are classified under that category. This implementation also requires a random number selection from between 0 and the length of each of the arrays, you can click \"this link\" to see how I made a random number selector that worked for arbitrary ranges.", supplies_image="/images/project-rooms/rooms-supplies.png"))
    db.session.add(Project(user_id=9, category_id=3, title="Ordinal Suffix Generator", description="The English language has an interesting quirk where ordered numberings have their own pronunciations. Using these can help communicate that things are of ordinal nature, however the inconsistent pattern of pronunciations can make implementing them programmatically non-trivial. In order to use them in various projects, I worked with some friends to make a function that takes a number and generates the ordinal pronunciation.", supplies_text="", supplies_image=""))

    db.session.commit()

def undo_projects():
    db.session.execute('TRUNCATE projects RESTART IDENTITY CASCADE;')
    db.session.commit()
