"""empty message

Revision ID: 04047b2f0322
Revises: 808a16e4cbea
Create Date: 2022-02-08 15:05:36.713227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04047b2f0322'
down_revision = '808a16e4cbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_image')
    # ### end Alembic commands ###
